#!/usr/bin/env bash
# This script installs and configures Nginx on an Ubuntu machine.

# Update package sources
apt-get update

# Install Nginx
apt-get -y install nginx

# Create a custom content file
echo "Hello World!" > /var/www/html/index.html

# Start Nginx (without using systemctl)
/etc/init.d/nginx start

# Nginx should be listening on port 80
# Test Nginx response
curl -sI 127.0.0.1 | grep "HTTP/1.1 200 OK" > /dev/null

if [ $? -ne 0 ]; then
    echo "Nginx is not listening on port 80"
        exit 1
	fi

echo "Nginx is up and running!"
