#!/usr/bin/env bash
# This script configures an Nginx server to have a custom 404 page.

# Install Nginx (if not already installed)
apt-get update
apt-get -y install nginx

# Create a custom 404 error page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Create Nginx configuration for the custom 404 page
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    error_page 404 /404.html;

    location / {
        try_files \$uri \$uri/ =404;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx
/etc/init.d/nginx restart

echo "Nginx configured with custom 404 page."
